language: php

services:
  - docker

php:
  - 7.4

before_script:
  - mkdir -p ./var/cache
  - mkdir ./var/cache/test ./var/cache/dev ./var/cache/prod
  - chmod 777 -R ./var
  - cp .env.dist .env
  - cp phpunit.xml.dist phpunit.xml
  - composer install -n
  - docker-compose up -d

script:
  - docker container exec ci_app php ./vendor/bin/phpunit

after_success:
  - docker-compose down
