language: php

sudo: false

services:
  - docker

php:
  - 7.3

# Build is failing in moment:
# https://docs.travis-ci.com/user/for-beginners/#breaking-the-build

# Travis and docker https://docs.travis-ci.com/user/docker/
# PHP in Travis https://docs.travis-ci.com/user/languages/php/

before_script:
  - mkdir -p ./var/cache ./build/logs
  - mkdir ./var/cache/test ./var/cache/dev ./var/cache/prod
  - chmod 777 -R ./var
  - cp .env.dist .env
  - composer install
  - cp phpunit.xml.dist phpunit.xml
  - docker-compose up -d

script:
  - docker container exec travis_app php ./vendor/bin/phpunit

after_success:
  - travis_retry docker container exec travis_app php vendor/bin/php-coveralls -v
  - docker-compose down -v