version: '3.7'

services:
  app:
    build:
      context: ./etc/
      dockerfile: apache2.dockerfile
    image: travis-app
    ports:
      - 80:80
    volumes:
      - ./:/var/www/html
    container_name: travis_app