version: '3'

services:
  app:
    build:
      context: ./etc/
      dockerfile: apache2.dockerfile
    image: ci-app
    ports:
      - 80:80
    volumes:
      - ./:/var/www/html
    container_name: ci_app
