version: 2
jobs:
  build:
    docker:
      - image: circleci/php:8-apache-browsers

    working_directory: /var/www/html

    steps:
      - checkout

      - run: sudo apt update
      - run: sudo apt-get install -y libpq-dev
      - run: sudo a2enmod rewrite
      - run: sudo cp etc/apache2.conf /etc/apache2/sites-enabled/000-default.conf

      - run: mkdir -p ./var/cache
      - run: mkdir ./var/cache/test ./var/cache/dev ./var/cache/prod
      - run: chmod 777 -R ./var
      - run: cp .env.dist .env
      - run: cp phpunit.xml.dist phpunit.xml
      - run: sudo service apache2 start

      - restore_cache:
          keys:
            - composer-v2-{{ checksum "composer.lock" }}
            - composer-v2-

      - run: ./composer.phar install -n

      - save_cache:
          key: composer-v2-{{ checksum "composer.lock" }}
          paths:
            - ./vendor

      - run: ./vendor/bin/phpcs
      - run: ./vendor/bin/phunit
      - run: ./vendor/bin/infection --min-covered-msi=70 --min-msi=70 -n
      - run: cat ./infection.log
